# Generated by Django 4.2.6 on 2023-10-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
